apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-website
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: simple.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-website
                port:
                  number: 80
